"""kpi

Revision ID: 3e191de89bb9
Revises: d196f931657f
Create Date: 2026-05-10 15:34:37.103263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e191de89bb9'
down_revision = 'd196f931657f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metric_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('manual_value', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'metrics', ['metric_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manual_value')
        batch_op.drop_column('direction')
        batch_op.drop_column('unit')
        batch_op.drop_column('metric_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
