"""add categories for all entity types

Revision ID: 6a90cc5e4821
Revises: d35882230304
Create Date: 2026-05-16 23:43:51.055595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a90cc5e4821'
down_revision = 'd35882230304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('datasource_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('widget_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.rename_table('categories', 'kpi_categories')

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('connection_string',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key(None, 'datasource_categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('dataset_fields', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('kpis_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'kpi_categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('aggregation_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint(batch_op.f('widgets_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'widget_categories', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('widgets_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.alter_column('aggregation_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('kpis_category_id_fkey'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('dataset_fields', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('connection_string',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('category_id')

    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.rename_table('kpi_categories', 'categories')

    op.drop_table('widget_categories')
    op.drop_table('datasource_categories')
    op.drop_table('dashboard_categories')
    # ### end Alembic commands ###
