"""add widget_metrics and widget_dimensions tables

Revision ID: bdb0521ff3bf
Revises: 475c64d504ae
Create Date: 2026-05-10 01:11:53.545244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb0521ff3bf'
down_revision = '475c64d504ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_dimensions',
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('widget_id', 'dimension_id')
    )
    op.create_table('widget_metrics',
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('widget_id', 'metric_id')
    )
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.alter_column('dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.alter_column('dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('widget_metrics')
    op.drop_table('widget_dimensions')
    # ### end Alembic commands ###
