"""add categories for dashboard

Revision ID: c620ff0be5bc
Revises: 6a90cc5e4821
Create Date: 2026-05-17 00:48:37.385945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c620ff0be5bc'
down_revision = '6a90cc5e4821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dashboard_categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('widgets_dataset_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'datasets', ['dataset_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('widgets_dataset_id_fkey'), 'datasets', ['dataset_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
