"""dashboard_widgets_m2m

Revision ID: d196f931657f
Revises: bdb0521ff3bf
Create Date: 2026-05-10 14:55:03.911523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd196f931657f'
down_revision = 'bdb0521ff3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_widgets',
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dashboard_id', 'widget_id')
    )
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('widgets_dashboard_id_fkey'), type_='foreignkey')
        batch_op.drop_column('position_x')
        batch_op.drop_column('position_y')
        batch_op.drop_column('width')
        batch_op.drop_column('height')
        batch_op.drop_column('dashboard_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('position_y', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('position_x', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('widgets_dashboard_id_fkey'), 'dashboards', ['dashboard_id'], ['id'], ondelete='CASCADE')

    op.drop_table('dashboard_widgets')
    # ### end Alembic commands ###
