"""add positions to dashboard_kpis

Revision ID: d35882230304
Revises: 3e191de89bb9
Create Date: 2026-05-10 16:01:46.541636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35882230304'
down_revision = '3e191de89bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('position_y', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_kpis', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
