"""update text-box

Revision ID: da194f8538ed
Revises: d466b5d142f8
Create Date: 2026-05-19 01:00:55.368443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da194f8538ed'
down_revision = 'd466b5d142f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_size', sa.String(length=8), server_default='base', nullable=False))
        batch_op.add_column(sa.Column('text_align', sa.String(length=8), server_default='left', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_texts', schema=None) as batch_op:
        batch_op.drop_column('text_align')
        batch_op.drop_column('font_size')

    # ### end Alembic commands ###
